export enum TypeQuestEnum {
  TEXTO = 'TEXTO',
  PARAGRAFO = 'PARAGRAFO',
  UNICA = 'UNICA',
  MULTIPLA = 'MULTIPLA',
  DATA = 'DATA',
  ESCALA = 'ESCALA',
  VERDADEIRO_FALSO = 'VERDADEIRO_FALSO',
  IMAGEM = 'IMAGEM',
  TEMPO = 'TEMPO',
  PONTUACAO = 'PONTUACAO',
}